version: "3.6"

services:
  splunk:
    image: splunk/splunk
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    volumes:
      - /input:/input
    ports:
      - 8000:8000


